version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - worlddb
    links:
      - worlddb
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@worlddb:5432/world_db
      - FLASK_ENV=development
      - FLASK_APP=run:app
    volumes:
      - ./:/app
    restart: unless-stopped
    command: ['./scripts/wait_for_it.sh', 'worlddb:5432', '--', './scripts/app_start_docker_compose.sh']

  worlddb:
    container_name: worlddb
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: world_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
