version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - worlddb
    links:
      - worlddb
    ports:
      - 5000:8080
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@worlddb:5432/world_db
    volumes:
      - ./:/app
    restart: unless-stopped

  worlddb:
    container_name: worlddb
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: world_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
