"""$1

Revision ID: 2a571de0908e
Revises: 054b2e0b8140
Create Date: 2022-05-09 02:20:40.226539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a571de0908e'
down_revision = '054b2e0b8140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('country_code', sa.String(length=3), nullable=False))
    op.drop_constraint('cities_countrycode_fkey', 'cities', type_='foreignkey')
    op.create_foreign_key(None, 'cities', 'countries', ['country_code'], ['code'])
    op.drop_column('cities', 'countrycode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('countrycode', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.create_foreign_key('cities_countrycode_fkey', 'cities', 'countries', ['countrycode'], ['code'])
    op.drop_column('cities', 'country_code')
    # ### end Alembic commands ###
