"""$1

Revision ID: 3611046d9877
Revises: 
Create Date: 2022-01-10 15:42:27.715609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3611046d9877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('continent', sa.String(length=127), nullable=False),
    sa.Column('region', sa.String(length=127), nullable=False),
    sa.Column('surfacearea', sa.Integer(), nullable=False),
    sa.Column('indepyear', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('lifeexpectancy', sa.Float(), nullable=True),
    sa.Column('gnp', sa.Float(), nullable=True),
    sa.Column('gnpold', sa.Float(), nullable=True),
    sa.Column('localname', sa.String(length=127), nullable=False),
    sa.Column('governmentform', sa.String(length=127), nullable=False),
    sa.Column('headofstate', sa.String(length=127), nullable=True),
    sa.Column('capital_id', sa.Integer(), nullable=True),
    sa.Column('code2', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('countrycode', sa.String(length=3), nullable=False),
    sa.Column('district', sa.String(length=127), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['countrycode'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('countries')
    # ### end Alembic commands ###
